spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root  
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/wechat?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    generate-ddl: true
server:
  context-path: /wechat    
  port: 8089
      